apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radicale.fullname" . }}
  labels:
    {{- include "radicale.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "radicale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radicale.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "radicale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
              - name: config
                mountPath: /etc/radicale/config
                subPath: config
              - name: rights
                mountPath: /etc/radicale/rights
                subPath: rights
              - name: users
                mountPath: /etc/radicale/users
                subPath: users
              - name: collections
                mountPath: {{ .Values.persistence.mount_point }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
          - name: config
            configMap:
                name: radicale-config
          - name: rights
            configMap:
                name: radicale-rights
          - name: users
            configMap:
                name: radicale-users
          - name: collections
            {{- if .Values.persistence.enabled }}
            persistentVolumeClaim:
              claimName: {{ include "radicale.fullname" . }}
            {{- else }}
            emptyDir: {}
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
