apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-rights
  labels:
    app: {{ template "radicale.name" . }}
    chart: {{ template "radicale.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  rights: |-
    # Allow reading root collection for authenticated users
    [root]
    user: .+
    collection:
    permissions: R

    # Allow reading and writing principal collection (same as user name)
    [principal]
    user: .+
    collection: {user}
    permissions: RW

    # Allow reading and writing calendars and address books that are direct
    # children of the principal collection
    [calendars]
    user: .+
    collection: {user}/[^/]+
    permissions: rw

